-- Persistent "shepherd over" rules. Each rule declares that a parent
-- person shepherds everyone matching the criteria. Rules are evaluated
-- whenever mappings or sync data change, producing tree_connections
-- with source_rule_id set so they can be wiped & regenerated cleanly.

CREATE TABLE IF NOT EXISTS shepherd_over_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL REFERENCES churches(id) ON DELETE CASCADE,
  parent_person_id uuid NOT NULL,
  parent_layer_id uuid NOT NULL REFERENCES tree_layers(id) ON DELETE CASCADE,
  rule_type text NOT NULL CHECK (rule_type IN ('group', 'team', 'group_type', 'team_type', 'layer')),
  rule_value text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shepherd_over_rules_church
  ON shepherd_over_rules(church_id);

-- Track which connections were generated by a rule so we can wipe + rebuild.
ALTER TABLE tree_connections
  ADD COLUMN IF NOT EXISTS source_rule_id uuid REFERENCES shepherd_over_rules(id) ON DELETE CASCADE;
